---
name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 3
      matrix:
        distro: [ubuntu-20.04]

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: DockerHub auth
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
      - name: Build docker image tag ${{ matrix.distro }} & push to dockerhub
        uses: docker/build-push-action@v2
        with:
          file: ${{matrix.distro}}/Dockerfile
          pull: true
          push: true
          tags: pmikus/docker-${{ matrix.distro }}-ansible:latest
      - name: Archive and upload Dockerfile
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.distro }}_image_artifacts
          path: ${{ matrix.distro }}/
